jetstreams:
  automata-bus:
    version: 2.10.10
    replicas: 1
    containerTemplate:
      resources:
        requests:
          cpu: 20m
          memory: 50Mi
          ephemeral-storage: 50Mi
        limits:
          memory: 100Mi
          ephemeral-storage: 100Mi
    streamConfig: |
      replicas: 1
    settings: |
      max_memory_store: 50Mi
      max_file_store: 50Mi
