image:
  repository: 795250896452.dkr.ecr.us-east-1.amazonaws.com/skunkworks/automata
  tag: latest

replicaCount: 1

services:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
    type: ClusterIP

ingress:
  enabled: true
  hosts:
    - automata.skunkworks.staging.corp.mongodb.com

mesh:
  enabled: true

envSecrets:
  GITHUB_APP_ID: automata-secrets
  GITHUB_APP_PRIVATE_KEY: automata-secrets
  GITHUB_WEBHOOK_SECRET: automata-secrets
  SENSOR_TOKEN: automata-secrets
  JIRA_BASE_URL: automata-secrets
  JIRA_API_TOKEN: automata-secrets

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    memory: 256Mi
