apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: automata-github
  namespace: skunkworks
  annotations:
    v1alpha1.argoslower.kanopy-platform/known-source: "github"
spec:
  eventBusName: automata-bus
  service:
    ports:
      - port: 80
        targetPort: 12000
  github:
    automata:
      repositories:
        - owner: mongodb
          names:
            - mongodb-atlas-cli
            - mongodb-atlas-local
            - apix-action
            - atlas-github-action
            - atlas-cli-core
            - atlas-cli-plugin-example
            - atlas-local-lib
            - atlas-local-cli
        - owner: mongodb-js
          names:
            - mongodb-mcp-server
            - atlas-local-lib-js
        - owner: 10gen
          names:
            - apix-dashboards
        - owner: mongodb-labs
          names:
            - cobra2snooty
            - automata
        - owner: mongodb-forks
          names:
            - chocolatey-packages
            - digest
      webhook:
        endpoint: /github
        port: "12000"
        method: POST
      webhookSecret:
        name: automata-secrets
        key: GITHUB_WEBHOOK_SECRET
      events:
        - "*"
      insecure: false
      contentType: json
