apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: automata-sensor
  namespace: skunkworks
spec:
  eventBusName: automata-bus
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
  dependencies:
    - name: github-dep
      eventSourceName: automata-github
      eventName: automata
  triggers:
    - template:
        name: call-automata
        http:
          url: http://automata-web-app.skunkworks.svc.cluster.local/webhook/github/argo
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: github-dep
                dataKey: headers.X-Github-Event.0
              dest: github_event
            - src:
                dependencyName: github-dep
                dataKey: headers.X-Github-Delivery.0
              dest: delivery_id
            - src:
                dependencyName: github-dep
                dataKey: body
              dest: body
          secureHeaders:
            - name: X-Automata-Token
              valueFrom:
                secretKeyRef:
                  name: automata-secrets
                  key: SENSOR_TOKEN
          timeoutSeconds: 30
