name: dependabot-merge
pipeline:
  - given:
      trigger: github
      repos:
        - mongodb-labs/automata
        # - mongodb/mongodb-atlas-cli
        # - mongodb/mongodb-atlas-local
        # - mongodb/apix-action
        # - mongodb/atlas-local-lib
        # - mongodb-js/atlas-local-lib-js
    when:
      - event: pull_request
        action: opened
        actor: dependabot[bot]
    then:
      - github.approve_pr:
          owner: "{payload.repository.owner.login}"
          repo: "{payload.repository.name}"
          number: "{payload.pull_request.number}"
      - github.enable_auto_merge:
          owner: "{payload.repository.owner.login}"
          repo: "{payload.repository.name}"
          number: "{payload.pull_request.number}"
          strategy: squash
