name: issue-sync-atlascli
pipeline:
  - given:
      trigger: github
      repos:
        - mongodb-labs/automata
        # - mongodb/mongodb-atlas-cli
        # - mongodb/atlas-github-action
    when:
      - event: issues
        action: opened
    then:
      - jira.create_issue:
          id: ticket
          issue_type: Story
          project: CLOUDP
          component: AtlasCLI
          custom_fields:
            customfield_12751: [{id: "22223"}]
            customfield_10257: {value: "Not Needed"}
          summary: "[{payload.repository.name}] {payload.issue.title}"
      - github.post_comment:
          owner: "{payload.repository.owner.login}"
          repo: "{payload.repository.name}"
          number: "{payload.issue.number}"
          body: "Jira ticket: {ticket.url}"

  - given:
      trigger: github
      repos:
        - mongodb-labs/automata
        # - mongodb/mongodb-atlas-cli
        # - mongodb/atlas-github-action
    when:
      - event: issues
        action: closed
    then:
      - github.list_pr_comments:
          id: comments
          owner: "{payload.repository.owner.login}"
          repo: "{payload.repository.name}"
          number: "{payload.issue.number}"
      - builtin.jq:
          id: find
          input: comments
          expr: 'first(.comments[].body | scan("CLOUDP-[0-9]+")) | {key: .}'
      - jira.transition:
          key: "{find.key}"
          transition_id: "1371"

  - given:
      trigger: github
      repos:
        - mongodb-labs/automata
        # - mongodb/mongodb-atlas-cli
        # - mongodb/atlas-github-action
    when:
      - event: issues
        action: reopened
    then:
      - github.list_pr_comments:
          id: comments
          owner: "{payload.repository.owner.login}"
          repo: "{payload.repository.name}"
          number: "{payload.issue.number}"
      - builtin.jq:
          id: find
          input: comments
          expr: 'first(.comments[].body | scan("CLOUDP-[0-9]+")) | {key: .}'
      - jira.transition:
          key: "{find.key}"
          transition_id: "3"
